### ISSUE TITLE
Add possibility to allow multiple CSS classes for one font

### ISSUE THREAD

**Issue by vaxul** [zachleat/postcss-foft-classes#2]
Hi,

I'd like to apply more than one CSS class for one web font.

For example:
```
.pipe(postcss([
  foftLoadedClasses({
	groups: [
	  {
		families: ['Taz'],
		classNames: [
		  ['js_fonts-loaded', 'no-js'],
		],
	  },
	],
   }),
]))
```

Which currently results in:
```css
.js_fonts-loaded,
no-js body {
  font-family: Taz
}
```

It should result in:
```css
.js_fonts-loaded body,
.no-js body {
  font-family: Taz
}
```

Here I'd like to ensure that the web font is loading even if JS (with FontFaceObserver) isn't available.

Would this be possible?

Best regards

vaxul
